config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'requirements#index'
  root to: redirect('/login')

  # Routes for Google authentication
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  get 'requirements', to: 'requirements#index'


  resources :comments
  post 'comments/new'
  resources :requirements do
    member do
      post 'vote'
      get 'vote'
      post 'down_vote'
      get 'down_vote'
      post 'new_comment'
      get 'new_comment'
      post 'create_comment'
      get 'create_comment'
    end
 end

 get 'requirements/filter'
 post 'requirements/filter'
resources :votes, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :requirement

  validates :body, presence: true # Valido que tenga comentario al crearlo.
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index; end

  def edit; end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :requirement_id, :utf8, :authenticity_token, :commit)
  end
end

app/views/comments/_form.html.erb
<%= form_for @comment, html: { class: 'form-horizontal'} do |f| %>
<div class='container-fluid'>
  <article class='box box-success'>
    <br>
    <div class='form-group'>
      <div class='row'>
        <div class='col-md-2'>
          <%= f.label :description, 'Descripcion' %>
          <strong>*</strong>
        </div>
        <div class='col-md-4'>
          <div class='input-group'>
            <%= f.text_area :body, rows: 15, cols: 50 %>
          </div>
        </div>
      </div>
  </article>
  <div class='row'>
    <div class='col-md-4'>
      <%= link_to 'Volver', requirements_path, {class:'btn btn-primary'} %>
      <%= f.submit 'Guardar', class: 'btn btn-success ' %>
    </div>
  </div>
</div>
</div>
<% end %>

<%= tinymce %>

app/views/comments/edit.html.erb
<section class='content'>
    <article class='box box-primary'>
        <div class='box-header'>
        <h1 class='box-title'>  <strong>Editar Comentario</strong> </h1>
        </div>
        <section class='box-body'>
          <%= render 'form', cached: true %>
        </section>
    </article>
</section>

app/views/comments/new.html.erb
<section class='content'>
    <article class='box box-primary'>
        <div class='box-header'>
        <h1 class='box-title'>  <strong>Crear Comentario</strong> </h1>
        </div>
        <section class='box-body'>
          <%= render 'form', cached: true %>
        </section>
    </article>
</section>