config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'requirements#index'
  root to: redirect('/login')

  # Routes for Google authentication
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  get 'requirements', to: 'requirements#index'


  resources :comments
  post 'comments/new'
  resources :requirements do
    member do
      post 'vote'
      get 'vote'
      post 'down_vote'
      get 'down_vote'
      post 'new_comment'
      get 'new_comment'
      post 'create_comment'
      get 'create_comment'
    end
 end

 get 'requirements/filter'
 post 'requirements/filter'
resources :votes, only: [:create, :destroy]
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  include RequirementFilters
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, :description, presence: true # Titulo y descripcion obligatorios

  # Calculo el total de votos de un requerimiento, teniendo en cuenta la entidad votes
  def score
     votes.where(vote_type: 1).count - votes.where(vote_type: 0).count
  end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
    before_action :find_requirement, only: %i[ edit update destroy]

    def index
      @requirements = Requirement.all # Usaria Presenter para poder enviar directamente a la vista
                                      # el modelo con todos sus elementos, podria agregar will_paginate, decorator
    end

    def new
      @requirement = Requirement.new
      respond_to do |format|
        format.html
        format.js
      end
    end

    def show; end

    def create
      @requirement = Requirement.new(requirement_params)
      if @requirement.save
        redirect_to requirements_path
        flash[:success] = 'Requerimiento Creado Correctamente'
      else
        flash[:danger] = 'Campo/s Obligatorios Incompleto/s'
        render :new
      end
    end

    def edit; end

    def destroy
      if @requirement.destroy
         flash[:success] = 'Requerimiento Eliminado'
         redirect_to requirements_path
      else
        flash[:danger] = 'Requerimiento no pudo ser eliminado'
        redirect_to requirements_path
      end
    end

    def update
      respond_to do |format|
        if @requirement.update(requirement_params)
          format.html do
            redirect_to requirements_path, notice: 'Requerimiento editado con exito'
          end
          format.json do
            render :show, status:
                               :ok, location: @requirement
          end
        else
          flash[:danger] = 'Campo/s Obligatorios Incompleto/s'
          render :edit

        end
      end
    end

    def vote
      @requirement = Requirement.find(params[:id])
      vote_saved = @requirement.votes.create(requirement_id: @requirement.id, user_id: params[:id], vote_type: params[:vote_type])
      redirect_to requirements_path
      flash[:success] = 'Votó exitoso' if vote_saved.errors.empty?
      flash[:danger] = 'Usted ya votó en este requerimiento'
    end

    def down_vote
      # Esto podria mejorarlo y directamente utilizar el action vote,
      # ya que puedo diferenciar con el tipo de voto (voto_type). Por cuestiones de tiempo no lo refactoricé
      @requirement = Requirement.find(params[:id])
      vote_saved  = @requirement.votes.create(requirement_id: @requirement.id, user_id: params[:id], vote_type: params[:vote_type])
      redirect_to requirements_path
      flash[:success] = 'Votó exitoso' if vote_saved.errors.empty?
      flash[:danger] = 'Usted ya votó en este requerimiento'
    end

    def filter
      @requirements = Requirement.filter_interface(params[:requirement])
      render 'requirements/filter.js.erb'
    end

    def new_comment
      @comment = Comment.new
    end

    def create_comment
      @comment = Comment.new(body: params[:comment][:body], user_id: @current_user.id, requirement_id: params[:id] )
      if @comment.save
        redirect_to requirements_path
        aux = flash[:success] = 'Comentario Creado Correctamente'
      else
        aux = flash[:danger] = 'Campo/s Obligatorios Incompleto/s'
        render :new
      end
    end

    private

    def filtering_params(params)
      params.permit(:by_vigency, :title, :votes)
    end

    def find_requirement
      @requirement = Requirement.find(params[:id])
    end

    def requirement_params
      params.require(:requirement).permit(:title, :description,:user_id,
                     :requirement_id, :vote_type, :authenticity_token, :id)
    end

    def vote_params
      params.permit(:user_id, :requirement_id, :vote_type, :id)
    end

    def comment_params
      params.permit(:user_id, :body, :user_id, :requirement_id, :utf8, :authenticity_token, :commit)
    end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/requirements/_filter.html.erb
<%= form_for(:requirement, url: requirements_filter_path, remote: :true ) do |f| %>
<div class='container-fluid'>
  <br>
  <div class='row'>
        <div class='col-sm-6'>
          <%= f.label :by_vigency, 'Ordenar por:' %>
          <%= f.select(:by_vigency,['Puntaje', 'Alfabetico'],
                { include_blank: ''}, { class: 'form-control' }) %>
        <br>
        <div class='col-md-12'>
          <%= f.submit 'Ordenar', class: 'btn btn-success btn-md pull-right',
                style: 'width:115px;',data: {disable_with: 'Espere...'} %>
        </div>
      </div>
      </div>
    <% end %>
  </div>

app/views/requirements/_form.html.erb
<%= form_for @requirement, html: { class: 'form-horizontal'} do |f| %>
<div class='container-fluid'>
  <article class='box box-success'>
    <br>
    <div class='form-group'>
      <div class='row'>
        <div class='col-md-2'>
          <%= f.label :title, 'Titulo' %>
          <strong>*</strong>
        </div>
        <div class='col-md-4'>
          <div class='input-group'>
            <%= f.text_field :title,class: 'form-control', required: true %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class='form-group'>
      <div class='row'>
        <div class='col-md-2'>
          <%= f.label :description, 'Descripcion' %>
          <strong>*</strong>
        </div>
        <div class='col-md-4'>
          <div class='input-group'>
            <%= f.text_area :description, rows: 10, cols: 50, class: "tinymce" %>
          </div>
        </div>
      </div>
  </article>
  <div class='row'>
    <div class='col-md-4'>
      <%= link_to 'Volver', requirements_path, {class:'btn btn-primary'} %>
      <%= f.submit 'Guardar', class: 'btn btn-success ' %>
    </div>
  </div>
</div>
</div>
<% end %>

<%= tinymce %>

app/views/requirements/_list.html.erb
<div id="filterrific_results_requirements">
  <div class='row'>
    <div class='col-md-12'>
      <table class='table table-bordered table-hover dataTable'>
        <thead>
          <tr role='row'>
            <th style="color:#3c8dbc;">Titulo</th>
            <th style="color:#3c8dbc;">Descripción</th>
            <th style="color:#3c8dbc;">Fecha Creación</th>
            <th style="color:#3c8dbc;">Cantidad Votos</th>
            <th style="color:#3c8dbc;">Comentarios</th>
            <th style="color:#3c8dbc;">Votar</th>
            <th style="color:#3c8dbc;">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <!-- Aca deberia agregar un decorator, para dejar mas prolija la vista, pero no llegué con el tiempo para entregarlo mas prolijo -->
          <% @requirements.each do |requirement| %>
            <tr>
              <td><%= requirement.title %>
              </td>
              <td><%= requirement.description.html_safe %>
              </td>
              <td><%= requirement.created_at.to_date %>
              </td>
              <td><%= requirement.score %></td>
              <td>
                <%= link_to 'Crear Comentario', new_comment_requirement_path(requirement), class: 'btn btn-primary btn-xs'%>
                <% requirement.comments.each do |comment| %>
                  <%= render( partial: 'requirements/modal_comments', locals: { comment: comment} ) %>
                <% end %>
              </td>
              <td>
                <%= button_to '+1', vote_requirement_path(requirement), params: { user_id: @current_user.id, vote_type: 1}, class: 'btn btn-success btn-xs' %>
                <%= button_to '-1', down_vote_requirement_path(requirement), params: { user_id: @current_user.id, vote_type: 0}, class: 'btn btn-danger btn-xs' %>
              </td>
              <td>
                <%= link_to 'Editar', edit_requirement_path(requirement), class: 'btn btn-primary btn-xs' %>
                <%= link_to 'Eliminar', requirement_path(requirement), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm:'¿Estas seguro que deseas eliminar este requerimiento'}%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class='col-md-6'>
      <button class='btn btn-primary btn-sm' onclick='topFunction()' id='myBtn'>
        Volver arriba!</button>
      <div class='container-fluid'></div>
    </div>
  </div>
</div>

app/views/requirements/_modal_comments.html.erb
<button type='button'  style='width:40px;'  class='btn btn-info btn-xs' data-toggle='popover'
data-content='<%="#{comment.body}"%>'>Leer</button>
 <!-- Modal -->
<script type="text/javascript">
 $(document).ready(function() {
  $('[data-toggle="popover"]').popover({
     placement: 'top',
     trigger: 'hover'
  });
 });
</script>

app/views/requirements/edit.html.erb
<section class='content'>
    <article class='box box-primary'>
        <div class='box-header'>
        <h1 class='box-title'>  <strong>Editar Requerimiento</strong> </h1>
        </div>
        <section class='box-body'>
          <%= render 'form', cached: true %>
        </section>
    </article>
</section>

app/views/requirements/filter.js.erb
$("#filterrific_results_requirements").html("<%=j render partial: 'requirements/list', locals: { requirements: @requirements} %>");

app/views/requirements/index.html.erb
<div class='container-fluid'>
  <div class='bg bg-info'>
    <strong><h3>Listado Requerimientos</h3></strong>
    <%= render( partial: 'requirements/filter', locals: { requirements: @requirements }, cached: true ) %>
  </div>
  <div class='col-md-6'>
    <%= link_to 'Crear Requerimiento',new_requirement_path, class: 'btn btn-primary btn-md' %>
  </div>
  <br>
  <br>
  <div class='col-md-12'>
    <br>
    <div class='bg bg-info'>
      <%= render( partial: 'requirements/list', locals: { requirements: @requirements }, cached: true ) %>
    </div>
  </div>
</div>

app/views/requirements/new.html.erb
<section class='content'>
    <article class='box box-primary'>
        <div class='box-header'>
        <h1 class='box-title'>  <strong>Crear Requerimiento</strong> </h1>
        </div>
        <section class='box-body'>
          <%= render 'form', cached: true %>
        </section>
    </article>
</section>

app/views/requirements/new_comment.html.erb
<%= form_for(@comment, url: create_comment_requirement_path, remote: :true ) do |f| %>
<div class='container-fluid'>
  <article class='box box-success'>
    <br>
    <div class='form-group'>
      <div class='row'>
        <div class='col-md-2'>
          <%= f.label :body, 'Haga un comentario' %>
          <strong>*</strong>
        </div>
        <div class='col-md-4'>
          <div class='input-group'>
            <%= f.text_area :body, rows: 10, cols: 50, required: true %>
          </div>
        </div>
      </div>
  </article>
  <div class='row'>
    <div class='col-md-4'>
      <%= link_to 'Volver', requirements_path, {class:'btn btn-primary'} %>
      <%= f.submit 'Guardar', class: 'btn btn-success ' %>
    </div>
  </div>
</div>
</div>
<% end %>

<%= tinymce %>

app/views/requirements/show.html.erb
<% if current_user %>
	<% current_user.attributes.each do |k, v| %>
		<b><%= k %>:</b> <%= v %> <br>
	<% end %>
<% end %>